export function tweetPrompt(researchData) {
  const prompt = `Imagine you are a content writer tasked with creating engaging tweets based on the provided research data. Your job is to generate 25 distinct tweets, each strictly under 250 characters, using the provided ${researchData}. Each tweet should consist of approximately two sentences that form a complete and valuable piece of content. In the first sentence, provide brief context and frame the point from your perspective as a content writer, naturally conveying what you found noteworthy, surprising, or significant about this specific piece of information. Avoid starting with generic phrases like 'Interesting finding:' or 'Key takeaway:' or any mini headings with a : in them. In the second sentences, deliver the crucial statistic, finding, or core information from the research data, along with its immediate implication or significance. Ensure the final sentence provides a clean conclusion for that specific point, avoiding an abrupt cutoff. Focus on extracting the most compelling insights from the research data. Craft these tweets with an authentic voice that reflects your genuine engagement with or reaction to the findings, rather than using overly formal or generic language. Ensure the tweets are accurate and well articulated, use accessible language, and cover a variety of points from the provided data. Your final output must be a single JSON object where the keys are sequentially named 'tweet 1', 'tweet 2', ..., 'tweet 25', and the corresponding value for each key is the generated tweet text string. Don't add markdowns to the output, the tweets should be in plain text. Don't quote the research data like "This article says" or "This is what the author says" or anything similar and please don't add special characters unless its absolutely necessary except the common ones like ".", ",", "'", "\"", "?", "!", ":", ";", "—", "-", "(", ")", "…", etc..`;

  return prompt;
}
export function tweetEvaluationPrompt(researchData, tweets) {
  const prompt = `Act as an expert Social Media Content Analyst and Fact-Checker. Your task is to evaluate a set of tweets based on the provided research data. You will be given two inputs: Research Data, provided in ${researchData}, which serves as the ground truth for factual accuracy, and Tweets JSON Data, provided in ${tweets}, a JSON object containing the tweets to be evaluated with keys like 'tweet 1', 'tweet 2', etc. Parse the Tweet JSON Data to extract the original tweet texts from these keys. For each tweet, assign ratings from 1 (lowest) to 10 (highest) for the following metrics: Readability (assessing conciseness, flow, and avoidance of dense jargon while retaining substance), Engagement Potential (judging how compelling, thought-provoking, and likely to generate interaction the content is), Quality & Insight (measuring the depth and value of the summary regarding research nuances). Calculate the overall average ratings for each metric across all tweets. Structure the output as a single JSON object containing only the JSON content, with no surrounding text. This JSON object must have two top-level keys: 'overall_average_ratings' (a dictionary mapping each metric name to its average score) and 'tweets' (a list of dictionaries). Each dictionary in the 'tweets' list should represent one tweet and contain the following keys: 'tweet_id' (the original key like 'tweet 1'), 'tweet_text' (the original, unmodified tweet text), 'ratings' (a dictionary of the five metric ratings), and 'suggestion' (a single, specific, actionable improvement suggestion for that particular tweet). Stick to the above format and don't add anything else. Ensure the output JSON is correctly formatted. Evaluate the tweets strictly based on the research provided in the research data. Do not assume or guess anything beyond what is explicitly stated in the research. If a tweet makes claims not clearly supported by the research data, deduct points from Factual Accuracy accordingly. Do not modify the original tweets in any way. Make sure the suggestions are more focused towards increasing the quality, insights and engagement potential of the tweets.`;

  return prompt;
}

export function evaluationBasedRegenerationPrompt(
  researchData,
  evaluatedTweets,
  tweets
) {
  const prompt = `Assume the role of a content writer tasked with refining a set of draft tweets. You will analyze the initial original tweet drafts provided in ${tweets} and the corresponding evaluated tweets provided in ${evaluatedTweets}, alongside the comprehensive ${researchData}. Your primary objective is to leverage the insights and findings within the research data to revise and enhance each draft tweet, ensuring it is compelling, accurate,engaging, and aligns with the research. While revising, adhere strictly to these guidelines for each tweet: maintain a strict character count under 250-260 you are not allowed to exceed this limit; structure the content into approximately three sentences; Focus on extracting the most compelling insights and crafting these tweets with an authentic voice that reflects genuine engagement with the research, rather than using overly formal language. You will focus on improving the readability, engagement potential, and quality & insight of the tweets and its going to be your number one priority. Your final output must be a single JSON object with 25 tweets as the original tweet draft where keys are sequentially named 'tweet 1', 'tweet 2', ..., 'tweet N' (matching the number of tweets evaluated/revised, indicated by 25), and the corresponding value for each key is the fully revised tweet text string. Don't quote the research data like "This article says" or "This is what the author says" or anything similar and please don't add special characters unless its absolutely necessary except the common ones like ".", ",", "'", "\"", "?", "!", ":", ";", "—", "-", "(", ")", "…", etc.`;

  return prompt;
}
